### ISSUE TITLE
Reporte de Práctica - Diagrama de secuencia.

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-equipo-fglr#1]
Práctica de diagrama de secuencia.

[Reporte de Práctica - Diagrama de Secuencia.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-equipo-fglr/files/7818313/Reporte.de.Practica.-.Diagrama.de.Secuencia.pdf)

**Comment by Brisa-4** [comment]
Calificación: 30%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
